name: 'ROBERT L KRAUS '
favicon: null
layout_spectrum: 0.37626759544946253
typography_spectrum: 0.16857780097052455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b9ab7'
    - '#c3c2c7'
    - '#09090b'
    - '#697a96'
    - '#2f2b2a'
  brandStrength: 0.3096155778039247
  lightness: 0.14934252528473735
  saturation: 0.6451439301017672
  rhythmicContrast: 0.9441644544713199
purpose: []
