name: 'ROBERT L KRAUS '
favicon: null
layout_spectrum: 0.49349
typography_spectrum: 0.16857780097052455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#ffffff'
    - '#7a583f'
    - '#c5853e'
    - '#ffd060'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
